### ISSUE TITLE
[nassl] use system openssl/zlib optionally

### ISSUE THREAD

**Issue by blshkv** [nabla-c0d3/sslyze#101]
I'm adding sslyze to Gentoo (Pentoo) repository and facing the problem. The latest nassl v0.12 has no option to use existing system libraries even if they meet all requirements.

Please specify which options of libraries must be enabled and allow to use system libraries.

My quick patch is here:
https://github.com/pentoo/pentoo-overlay/commit/dd9d21cdcb2aee07cdbec25b81c81d1c5f703395

**Comment by nabla-c0d3** [comment]
Hi - thanks for doing this. Using the OS' OpenSSL is not something I plan on officially supporting (I've tried before and there are too many moving parts). However, the current version of nassl should work with the 1.0.2 branch of OpenSSL. Some checks might still fail if OpenSSL was not compiled with compression enabled. Do you need more information ?

**Comment by blshkv** [comment]
In gentoo, a package can influence on system libraries and  enable required options. That's the reason why we unbundle all dependences if possible.  I found the requirements in setup file and here what I did: https://github.com/pentoo/pentoo-overlay/commit/3ae076f12d3dadd2152386efb0f69e4eb1ef55d4
So it would really help if it would be a legal switch. Something like "--use-system-libraries" would do it.

**Comment by nabla-c0d3** [comment]
Using the system library will definitely no longer be supported because of #116. Nassl is now using a fork of OpenSSL 1.0.2e in order to get extra features (but it's still binary compatible with 1.0.2e). 

However, I have finally put nassl on PyPi and will add SSLyze soon, meaning that it can be installed by just using `pip install sslyze`. That should enable users to get it on Gentoo and it should solve your packaging problems, I think ?

**Comment by blshkv** [comment]
no problem at all. Please clone it with a different name so we could add that package as a dependency and replace system openssl

**Comment by nabla-c0d3** [comment]
Just to clarify, what do you mean by cloning it with a different name ? In the build script for nassl ?

**Comment by blshkv** [comment]
In Gentoo we use slots and can install multiple versions if required.
In case of openssl:
```
dev-libs/openssl
     Available versions:  
     (0.9.8)  0.9.8z_p7 0.9.8z_p8
     (0)        1.0.1p
```
I guess, we will have 1.1.0 slot soon. As you can see we still can install 0.9.8 line.

I'm not sure about the purpose of the fork. But if you worry that the 1.0.2 line will just disappear I suggest to fork with openssl102 name or similar. You would need to maintain it and backport all security patches

**Comment by blshkv** [comment]
can we come back to this topic?
The tool seems does no longer use forks. 
It requires legacy openssl-1.0.2e and zlib-1.2.11 without any modifiction.
It is also requires modern openssl (a snapshot).

Can you introduce additional switches which would allow to enable each system library individually?

**Comment by nabla-c0d3** [comment]
Yes, I did get rid of the OpenSSL fork. Right now nassl uses:

* Zlib 1.2.11
* OpenSSL 1.0.2e
* OpenSSL 1.1.1 beta

I honestly don't have time to figure out how to build the whole thing using system libraries instead of source. 
Is there anything on your side that prevents building from source? All gets statically linked into nassl and the final binary is pretty small (only a few mB), so it should be fine? It also avoids having to install two different versions of OpenSSL on the system just to run nassl.

**Comment by blshkv** [comment]
well, the thing is we don't like static libs since we can recompile a lib as required.
So if you could introduce a flag to look for a system library that would be perfect.
Something like "--system-legacy-openssl-andIknowWhatImDoing will do it ;-)

**Comment by blshkv** [comment]
btw, I'm not sure why, but both openssl 1.0.2o and 1.1.1_pre7 are under the same slot in Gentoo, meaning both can't be installed at the same time, at least for now. That probably means that they are compatable and 1.1.1 can be used without 1.0.2 requirement? Can you review it please?

```
[I] dev-libs/openssl
     Available versions:  
     (0.9.8) 0.9.8z_p8^d 0.9.8z_p8-r1^d
     (0)    1.0.2o-r3^d ~1.0.2o-r6^d [M]~1.1.0h-r2(0/1.1)^d [M]**1.1.1_pre7-r1(0/1.1)^d
```
 
Edit: for legacy, the following libraries can be used:
```
* dev-libs/openssl-compat
     Available versions:  
     (0.9.8) 0.9.8z_p8-r2^td
     (1.0.0) 1.0.2u-r2^td
and
* dev-libs/openssl-bad [1]
     Available versions:  1.0.2_p20180915^d 1.0.2_p20190119^
```

openssl-bad fork has all weak ciphers enabled, and it is used by testssl.sh

**Comment by nabla-c0d3** [comment]
That's one of the problems with using the systems libraries. Nassl needs to be compiled with both exact versions of OpenSSL: 1.0.2e and 1.1.1 beta. Any other version will not work, and both are needed. 
All in all I have no plans to support building with system libraries - it is too unlikely to even work due to how different nassl's use case is.

**Comment by blshkv** [comment]
ok, that explains. I will stop trying to make it right since the tool is so tied to specific versions.
