### ISSUE TITLE
invalid target if no ciphers/ssl version successfull

### ISSUE THREAD

**Issue by krajorama** [nabla-c0d3/sslyze#128]
Hi,

I have an automated test that compares sslyze xml output to predefined expected results. Upgrading from 0.12 to 0.13.3 broke the test in two ways:
- Empty "<"acceptedCiphers/">" tag is not present if there are no accepted ciphers for some, but not all SSL versions. This seems logical, and I've fixed my expected results.

-  Invalid target is reported instead of empty "<"sslv1/">", "<"tlsv1/">", etc tags, when none of the ciphers were successful for any ssl version.

To put it short: what's the reasoning behind these lines? In server_connectivity.py:
if ssl_version_supported is None or ssl_cipher_supported is None:
            raise ServerConnectivityError(self.CONNECTIVITY_ERROR_HANDSHAKE_ERROR)

regards, krajo

**Comment by nabla-c0d3** [comment]
Hi,
The change that happened here is that in 0.13.x, SSLyze will try all possible ciphers and ssl versions at the very beginning, in order to find which ones work with the server. If none of them work, it means that SSLyze is basically unable to complete an SSL handshake with the server and there is no point in actually trying to scan it (with --sslv3 and other commands), hence the ServerConnectivityError.

**Comment by krajorama** [comment]
Fair enough, I'll update my test case. 
However, please make sure to only use the associated error text ("Could not complete an SSL handshake") with this specific case so that it doesn't start to show up in some unrelated case.

regards, krajo

**Comment by acdha** [comment]
A colleague just encountered this error while locking down a Java app where some clients (Mac, Ubuntu 14.04 LTS) couldn't connect using old versions of OpenSSL or gnutls – would it be a reasonable amount of work to have it display the received ciphersuite for troubleshooting?
