### ISSUE TITLE
www.vba.va.gov breaks XML output

### ISSUE THREAD

**Issue by postmodern** [nabla-c0d3/sslyze#162]
### Steps to Reproduce
1. `./sslyze_cli.py --regular --xml_out test.xml www.vba.va.gov`
### Backtrace

<pre>
Traceback (most recent call last):
  File "./sslyze_cli.py", line 677, in <module>
    main()
  File "./sslyze_cli.py", line 661, in main
    xml_final_pretty = minidom.parseString(xml_sanitized_final_string).toprettyxml(indent="  ", encoding="utf-8" )
  File "/usr/lib64/python2.7/xml/dom/minidom.py", line 1928, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib64/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "/usr/lib64/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 40, column 2921
</pre>

Tested on 0.13.6 and master.

**Comment by nabla-c0d3** [comment]
The subject alternative name returned by OpenSSL has an ambiguous field, which confuses SSLyze when parsing, it leading to an <iit@va.gov> (invalid) XML tag:

        X509v3 extensions:
            X509v3 Subject Alternative Name:
                email:gerald.mcmanus@va.gov, iit@va.gov

If there are multiple emails, it should be:

                email:gerald.mcmanus@va.gov, email:iit@va.gov

It is probably because the actual field in the certificate is `gerald.mcmanus@va.gov, iit@va.gov`. I'll think of a solution when I have time.

**Comment by nabla-c0d3** [comment]
Fixed in https://github.com/nabla-c0d3/nassl/commit/2d33bc06220967cd9bbdb0db28221e4c2ca59022 .
