### ISSUE TITLE
Won't check SHA1 when the certificate is not valid

### ISSUE THREAD

**Issue by glestel** [nabla-c0d3/sslyze#187]
With the update to 0.14.x the SHA1 verification has been moved in the xml. And if the certificate is not valid (expired, self-signed, or untrusted root) the `hasSha1SignedCertificate` tag won't be present. But it will be present if the certificate is valid on a wrong hostname.
I think it will be more consistent for post-analysis if the tag was available in any use case, and even if the certificate is untrusted, the SHA1 info should not be dismissed because it is still relevant to list all of the issues an URL could have.

**Comment by nabla-c0d3** [comment]
The `hasSha1SignedCertificate` tag is meant to let you know if the server's certificate chain will cause problems with the deprecation of SHA1 in browsers ( https://blog.qualys.com/ssllabs/2014/09/09/sha1-deprecation-what-you-need-to-know ). That's the case if a certificate in the chain has been signed with SHA1 but it does not apply to the anchor/CA certificate. Hence, SSLyze needs to first build the verified chain in order to know which certificate is the anchor certificate (which can't be done for self-signed certificates).

If you're only interested in finding any SHA1 certificate, you can directly read the certificates' attributes using `--certinfo_basic` .
