### ISSUE TITLE
XML DTD

### ISSUE THREAD

**Issue by postmodern** [nabla-c0d3/sslyze#19]
I'm working on a [ruby wrapper](https://github.com/trailofbits/sslyze) to automate sslyze and parse the resulting XML output (a la [ruby-nmap](http://rubydoc.org/gems/ruby-nmap/frames)). I was wondering if you had a complete DTD for the XML output?

**Comment by blshkv** [comment]
this should be probably related:
https://github.com/iSECPartners/sslyze/issues/42

**Comment by nabla-c0d3** [comment]
I created an xml_out.xsd schema which passes all the test cases in ./test/. It cannot handle all possible XML documents generated by SSLyze because of the infinite number of X509 extensions and certificate fields in general. If I missed something important feel free to open a new issue or a pull request.
