### ISSUE TITLE
Readme: Additional requirements for Linux

### ISSUE THREAD

**Issue by wendelb** [nabla-c0d3/sslyze#228]
Hi there,

I was trying to install this tool on my Ubuntu Server. The installation failed to compile the `cryptography` requirement because the file `openssl/opensslv.h` was missing. This can be solved by installing `libssl-dev`.

Would you please be so kind and add that to the readme?

Kind regards.

**Comment by glestel** [comment]
On a clean linux install, I run into some hiccups with `unable to execute 'x86_64-linux-gnu-gcc': No such file or directory` meaning I had to install `gcc` and `build-essential`, then `nassl/_nassl/nassl.c:1:20: fatal error: Python.h: No such file or directory` meaning I had to install `python-dev`, and finally `c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory` needing to install `libffi-dev`,  in addition to your issue.
Looking up the cryptography requirement for installation, before installing `sslyze` you might need to install ` build-essential libssl-dev libffi-dev python-dev` on a fresh Linux installation

**Comment by savahu** [comment]
Thanks a lot for explaining the undocumented dependencies!

**Comment by nabla-c0d3** [comment]
On Linux the cryptography package does not require any dependency (https://cryptography.io/en/latest/installation/) so you should not have to install `libss-dev` if you followed the instructions in the README. You only need these dependencies if you are trying to build `cryptography` but that's a more advanced use case.  

The `typing` module is specified in the requirements file so that should be fine too. 

Hence I don't think there's anything missing from the README?

**Comment by redtrumpet** [comment]
Maybe this is a bug in the cryptography package, but I also run into these issues. I used `pip install sslyze --user` to install. I also had to install `libffi-dev`. Not sure if `pip` tries to build the cryptography package?
