### ISSUE TITLE
Auto prepend 'www' to domains

### ISSUE THREAD

**Issue by refayathaque** [nabla-c0d3/sslyze#352]
Hello,

Thank you so much for building this tremendous library. I was wondering if you guys were planning on adding a feature where domains being scanned will auto-prepend 'www'. We are getting completely different results for some of the domains we are scanning for vulnerabilities, e.g., samhsa.gov will result in an unsuccessful connection, whereas www.samhsa.gov will work flawlessly.

Thank you again,

**Comment by nabla-c0d3** [comment]
Hello,
www.domain.com and domain.com are just two different domains which is why you are seeing different results. A DNS record can be set to automatically redirect the naked domain to www, but this is not something that has to do with Sslyze; it will scan whatever domain it is given and that’s the “correct” behavior.
