### ISSUE TITLE
hsts problems

### ISSUE THREAD

**Issue by Xurcr0h** [nabla-c0d3/sslyze#44]
If I try --hsts its not giving me the right results. It says no hsts supported by facebook for example. But they support hsts, if I check the headers.
Whats the problem? thx

**Comment by nabla-c0d3** [comment]
Hi,
I checked the headers returned by https://www.facebook.com and didn't HSTS.

**Comment by Xurcr0h** [comment]
If I check them with Live HTTP headers (or firebug) I get a Strict-Transport-Security:max-age=15552000:preload
Thats strange

**Comment by nabla-c0d3** [comment]
Try again when you're not logged in ?

**Comment by Xurcr0h** [comment]
Still the same

**Comment by Xurcr0h** [comment]
Checked on another notebook and got the same result

**Comment by nabla-c0d3** [comment]
I did a quick investigation and www.facebook.com doesn't always send the HSTS header; it is based on the User-Agent received (perhaps so that they don't send the HSTS header for user agents that don't support it anyway). Not really something I can fix, unless I change sslyze's user agent, which doesn't seem like a good idea.
