### ISSUE TITLE
sslyze as Reverse Proxy

### ISSUE THREAD

**Issue by teodem** [nabla-c0d3/sslyze#442]
**Is your feature request related to a problem? Please describe.**
I am using SSLyze in gitlab CI.
To make my automated security scan project, I would like to integrate current tests with SSLyze.

**Describe the solution you'd like**
To do this, however, I don't want to pass a specific "target" between the variables, but I want to pass a source where i want to receive the traffic to be scanned (localhost for example). In practice, I would like to use a Daemon version of SSLyze, as a reverse proxy.

**Describe alternatives you've considered**
I have read the documentation very carefully but have found nothing that can remedy this problem. Also, the further difficulty would be to use this daemon in Docker.

**Comment by nabla-c0d3** [comment]
I am not sure I understand what you're asking for. SSLyze works by connecting to the server and sending special payloads in order to see how it reacts. It cannot "scan" traffic sent by a different client to the server; SSLyze has to be the client connecting to the server. Feel free to reopen this if I misunderstood the request.
