### ISSUE TITLE
post_handshake_response removed from cipher_suite object

### ISSUE THREAD

**Issue by PreflightOptions** [nabla-c0d3/sslyze#460]
Updating tooling that implements Sslyze as a library to the 3x branch and I noticed that the post_handshake_response variable seems to have been dropped. 

Was this intended and it's not coming back?

**Comment by nabla-c0d3** [comment]
It was dropped to make scans faster - what was your use case with it?

**Comment by PreflightOptions** [comment]
Certain applications still accept a given protocol but do not allow application function such as Salesforce instances. They redirect to a "connection not allowed" page. It was useful to display.

**Comment by nabla-c0d3** [comment]
Yeah that was the point of post_handshake_response(), but showing the response/redirection was misleading because this behavior is insecure regardless of the error page. 

A connection with broken crypto can be compromised by an attacker who then fully controls the content of the response (and can for example mitm the connection), so the error page doesn't really do anything.
