### ISSUE TITLE
Certificate is not trusted (Even updated cert store)

### ISSUE THREAD

**Issue by r0oth3x49** [nabla-c0d3/sslyze#523]
**Describe the bug**
I was testing sslyze against `impactechs.com`, sslyze says certificate is not trusted for all trust stores (mozilla, android, java etc).

**To Reproduce**
1. Installed sslyze using pip (the latest version)
2. Run the following command `sslyze --certinfo impactechs.com`
4. the error will say for all store the cert is not trusted, unable to fetch local issuer.

**Expected behavior**
The certificate should be trusted the web is behind cloudflare when i run sslyze against IPs assigned to that website then the cert store trust the certificate but not against the domain.

**Python environment (please complete the following information):**
 - OS:  Ubuntu 20.04.2 LTS
 - Python version: 3.8.10

**Additional context**
Ran ssllabs against the same domain and it reports no trust issues while sslyze does.
![sslabs](https://user-images.githubusercontent.com/11024397/126860509-3bae2594-26ef-446d-b1c8-1d009265a3e8.PNG)
![sslyze](https://user-images.githubusercontent.com/11024397/126860525-c49d5594-1b5b-4019-9bdf-eba9f8cc4aa7.PNG)

**Comment by nabla-c0d3** [comment]
Hello,
This is because the certificate chain sent by the server is incomplete; SSLyze is unable to build the chain. It's also flagged by SSL Labs:

<img width="484" alt="Screen Shot 2021-09-25 at 2 37 18 PM" src="https://user-images.githubusercontent.com/1915165/134786608-fa8fabd9-6409-406e-ac45-21e3432ac41c.png">

You would have to tweak the server's configuration so that it does return the missing intermediate certificate (Sectigo RSA Domain Validation Secure Server CA).
