### ISSUE TITLE
Release 0.12

### ISSUE THREAD

**Issue by postmodern** [nabla-c0d3/sslyze#89]
Wondering when 0.12 will be released. Issue #81 prevented me from upgrading to 0.11.

**Comment by nabla-c0d3** [comment]
Most likely September.

**Comment by dbaxa** [comment]
@nabla-c0d3 perhaps can you release a new 0.11.X version that includes the fixes you have made since 0.11.x was released (such as #73) ?

**Comment by konklone** [comment]
A new release would help me out too -- I'm integrating `sslyze` into something, and #73 is making it harder to understand SHA-1 deprecation.

**Comment by fishouttah20** [comment]
Similarly I could really do with a 0.12 to resolve #77 on 64bit Windows. I'd build it myself but the Readme states "If you want to clone the SSLyze repo, you will have to get a compiled version of nassl from one of the SSLyze packages and copy it to sslyze-master/nassl, in order to get SSLyze to run." but I don't see a compiled version of nassl in the Windows release. Maybe I'm misinterpreting.

**Comment by nabla-c0d3** [comment]
I stopped providing 64 bits builds for Windows (they're really hard to compile). I will try to release 0.12 asap.

**Comment by fishouttah20** [comment]
Ah, that explains it. Thanks very much.

**Comment by tam7t** [comment]
PR for update in homebrew: https://github.com/Homebrew/homebrew/pull/44303

**Comment by nabla-c0d3** [comment]
thanks :)
